#!/usr/bin/env node
/*eslint-disable no-sync */
var fs = require( 'fs' );
var path = require( 'path' );

var rc = require( 'rc' );
var babel = require( 'babel-core' );
var _ = require( 'lodash' );

var defaults = JSON.parse( fs.readFileSync( path.resolve( __dirname, '../.babelrc' ) ) );
var config = _.merge( {}, defaults, rc( 'babel' ) );

babel.register( {
	'extensions': config.extensions,
	'blacklist': config.blacklist,
	'whitelist': config.whitelist,
	'optional': config.optional,
	'ignore': config.ignore,
	'stage': config.stage
} );

require( './_boilerplate-server' );
