#!/usr/bin/env node
/*eslint-disable no-process-env */
import { resolve } from 'path';

import minimist from 'minimist';
import server from '../';

const args = minimist( process.argv.slice( 1 ) );

export default async function start ( options = {} ) {
	let augmented = Object.assign( {}, {
			'cwd': process.cwd(),
			'base': resolve( __dirname, '../' ),
			'env': process.env.NODE_ENV || 'development'
		}, options, { 'api': options } );

	return await server( augmented );
}

start( args )
	.then( function startCompleted ( application ) {
		application.log.info( '[application]', 'Started server ...' );
	} )
	.catch( function startFailed ( err, application ) {
		let log = application ? application.log || console : console;

		log.trace( err );
	} );
